version: '3.8'

services:
  postgres_tenant:
    image: postgres:15.3
    container_name: postgres_tenant
    environment:
      POSTGRES_USER: g2dev
      POSTGRES_PASSWORD: g2dev-123456
      POSTGRES_DB: tenant1
      POSTGRES_ROOT_HOST: '%'
    ports:
      - "5432:5432"
    volumes:
      - ../.docker/postgres_tenant:/var/lib/postgresql/data

  postgres_tenant_2:
    image: postgres:15.3
    container_name: postgres_tenant_2
    environment:
      POSTGRES_USER: g2dev
      POSTGRES_PASSWORD: g2dev-123456
      POSTGRES_DB: tenant2
      POSTGRES_ROOT_HOST: '%'
    ports:
      - "5433:5432"
    volumes:
      - ../.docker/postgres_tenant2:/var/lib/postgresql/data

volumes:
  postgres_bff:
        driver: local