create table tenant_client (
    id int8 generated by default as identity,
    name varchar(255),
    url  varchar(255),
    tenant_name varchar(100),
    schema_name varchar(100),
    username varchar(100),
    password varchar(100),
     primary key (id)
);